apiVersion: v1
kind: BuildConfig
metadata:
  name: sample-pipeline
  labels:
    name: sample-pipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node("maven") {
          stage("echo") {
            println("Hello World")
          }
        }
